# Generated by Django 5.0.6 on 2024-07-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
