# Generated by Django 5.0 on 2024-01-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.deliveryplace'),
        ),
    ]
