# Generated by Django 5.0.6 on 2024-08-29 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess_name', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sts', models.CharField(default='active', max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_name.mess')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('tk', models.FloatField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.student')),
            ],
        ),
    ]
