# Generated by Django 5.0.6 on 2024-08-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement',
        ),
        migrations.AddField(
            model_name='project',
            name='backend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
